// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lolqnrptkjtfquohchkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbHFucnB0a2p0ZnF1b2hjaGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNDA4NzQsImV4cCI6MjA1NDYxNjg3NH0.tEBkfWbcZRLcEn6BnBDtlZLpeHH3pVJ76o5JLl5WXaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);